### ISSUE TITLE
docs errors

### ISSUE THREAD

**Issue by jonschlinkert** [doowb/view-get-dest#1]
Headings in the API docs are wrong. https://github.com/doowb/view-get-dest#view-get-dest

**Comment by doowb** [comment]
Meaning I should call it `getDest` or something else?

**Comment by jonschlinkert** [comment]
no, it's not a method, it's the main export. that and dashes would throw an error :)

**Comment by doowb** [comment]
How do I remove the `.` from the name?

**Comment by doowb** [comment]
Figured it out... removed the `@name` attribute and just named the exported function.
Thanks for pointing it out.
